### ISSUE TITLE
Remove blue outline on search field

### ISSUE THREAD

**Issue by LindseyWagner** [cityofsomerville/cornerwise#219]
<img width="593" alt="screen shot 2016-03-01 at 7 08 29 pm" src="https://cloud.githubusercontent.com/assets/1194582/13446370/0ab0513c-dfe1-11e5-8a07-c62509db8bbd.png">

**Comment by danjmoore** [comment]
Commit [bc0bb4e](https://github.com/cityofsomerville/cornerwise/commit/bc0bb4e58873c761981eeb88bf9604adbacb6f21) removes the blue border that's generated by mouseclicks, but not those from keyboard input. This lets us get the classy look without hurting accessibility. BUT, since the first input field gets focused on programmatically and not via mouse, it's still showing up there. Should we prevent that field from being selected on page load?
